# This will not run on Travis' 'new' container-based infrastructure
sudo: required

language: csharp

notifications:
  email: false

# Blacklist
branches:
  only:
    - master

# Environment variables
env:
  global:
    - GH_REPO_NAME: tModLoader
    - DOXYFILE: $TRAVIS_BUILD_DIR/solutions/documentation/Doxyfile
    - GH_REPO_REF: github.com/tModLoader/tModLoader.git

# Install dependencies
addons:
  apt:
    packages:
      - doxygen
      - doxygen-doc
      - graphviz

#before_install:
#    - sudo apt-add-repository -y ppa:mikepurvis/docs
#    - sudo apt-get update
#    - sudo apt-get install doxygen
      
# Build your code e.g. by calling make
script:
  - pwd
  - doxygen -v
  - ls

# Generate and deploy documentation
after_success:
  - cd $TRAVIS_BUILD_DIR
  - chmod +x solutions/documentation/generateAndPublishDocumentation.sh
  - ./solutions/documentation/generateAndPublishDocumentation.sh
